### ISSUE TITLE
Create KMS Module

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/delivery-aws-iac#175]
Now that the KMS key is expected to be created outside of the S3 module, it would be helpful to provide a simple module to create a KMS key in the appropriate manner

**Comment by RothAndrew** [comment]
@runyontr Can you help us collect a bit more information? What is the current "pain point" you are experiencing?

* Is the issue one of speed? That we could save people time by doing upfront work to maintain a module so that people don't need to make as many decisions and do as much work in order to have a KMS key that follows best practices?
* Is the issue one of knowledge/experience? Is it overly hard to create a secure KMS key, such that we may want to create a module that simplifies the options in an opinionated way?
* Is it something else?

I have a feeling that in reality it is a combination of things, but identifying what the biggest pain point is may help us target our efforts better to get something out more quickly.

How are you using these modules? They are mostly focused on certain specific delivery efforts. We realize other users are using them for other use cases, but the trigger hasn't been pulled yet on maintaining them as reusable OSS yet.

**Comment by runyontr** [comment]
With the removal of making the KMS key [here](https://github.com/defenseunicorns/iac/pull/141), its now expected that someone has a useful/functioning key that has been configured via the terraform in [this file](https://github.com/defenseunicorns/iac/blob/main/examples/complete/access-logging.tf) (presumably).  Not understanding the permissions and objects being created, having a re-usable and secure object that I can count on not misconfiguring would give me the confidence I need to ensure I'm making the KMS key and configuring it correctly.

**Comment by RothAndrew** [comment]
Copy, thanks. I think a good first stab would be to create a module that surfaces the options that we want configured and hard-codes the ones we want opinionated, would be helpful. The biggest challenge will probably be the IAM policy, since there isn't really a "one size fits all" set of permissions, and what we use now is likely too loose (uses `resources = ["*"]` and allows both `kms:Encrypt` and `kms:Decrypt` at the same time)

If we give good documented examples of policies that follow best practice we may be able to guide people toward what they need without being too restrictive.

**Comment by RothAndrew** [comment]
Module located here: https://github.com/defenseunicorns/uds-iac-aws-kms
