### ISSUE TITLE
"Access denied" when attempting to create PVC backed by EFS

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/delivery-aws-iac#228]
### Persona

Submitting on behalf of a user who is using this repo to stand up an EKS cluster, and is having problems when trying to use the EFS-backed storageclass

### Description

> I get "access denied" when the provisioner attempts to create a volume

### Use Case

EFS is super important to our users, as it is the easiest way to get reliable (though not particularly performant) PVCs that are cross-AZ and able to be created in Read-Write-Many (RWX) mode.

Our E2E tests that utilize the example root module enables EFS, but doesn't currently verify its functionality.

### Impact

EFS-related functionality will continue to be "non-definitive" since it is a testing gap

### Completion

The E2E test(s) verify that the user is able to provision PVCs backed by EFS. Exact method of that verification is left up to the implementer.

**Comment by corang** [comment]
To add to this, the issue was encountered after deleting and re-creating the efs-csi-driver via tf, so that the reclaimpolicy could be changed

**Comment by RothAndrew** [comment]
That's a good data point for that particular environment, thanks. At this point we aren't even able to definitively say whether the baseline EFS configuration is "known good", which is what implementing this would address.

**Comment by corang** [comment]
> That's a good data point for that particular environment, thanks. At this point we aren't even able to definitively say whether the baseline EFS configuration is "known good", which is what implementing this would address.

Lol, I'll let you know if it is soon

**Comment by ntwkninja** [comment]
Problem #1 - In AWS GovCloud, [enable_efs=true](https://github.com/defenseunicorns/delivery-aws-iac/blob/main/examples/complete/fixtures.common.tfvars#L86) does not provision a file system as intended due to permissions in the IAM policy attached to the EFS service account role.

Problem #2 - In AWS GovCloud, when a PVC is invoked by a pod the EFS file system policy does not allow an EFS access point to be created (could also be related to #1 but is a separate issue).

Feature Request: Add FIPS VPC endpoint for EFS and configure EFS to use it

**Comment by RothAndrew** [comment]
Created #239 based off of this feedback
